name: device_marketing_names
description: Lookup device marketing names for Android, iOS and browsers with ease. No internet connection or database required.
version: 0.3.1
homepage: https://github.com/Boehrsi/device_marketing_names

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter
  device_info_plus: ^3.2.1
  universal_platform: ^1.0.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.1.7
  device_info_plus_platform_interface: ^2.3.0
  flutter_lints: ^1.0.4
  mockito: ^5.0.17

flutter: