name: device_marketing_names
description: Lookup device marketing names for Android and iOS with ease. No internet connection or database required.
version: 0.1.0
homepage: https://github.com/Boehrsi/device_marketing_names

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter
  device_info_plus: ^3.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.4

flutter: