name: device_marketing_names
description: Lookup device marketing names for Android, iOS and browsers with ease. No internet connection or database required.
version: 0.4.1
homepage: https://github.com/Boehrsi/device_marketing_names

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter
  device_info_plus: ^3.2.4
  universal_platform: ^1.0.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.1.11
  device_info_plus_platform_interface: ^2.3.0+1
  flutter_lints: ^2.0.1
  mockito: ^5.2.0

flutter: